title: Advanced Control for Robotic
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://SuDaxia-kai.github.io/test

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
