title: Advanced Control for Robotic
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://SuDaxia-kai.github.io/test

logo: "/assets/images/assets/images/cropped-logo-green-03.png"

aux_links:
  CLEAR_LAB: https://space.bilibili.com/474380277?spm_id_from=333.337.0.0

nav_enabled: false
